//! Auto Generated by Python driver on 2022-10-26 15:00:50.650612 
//! author: channa@ambientscientific.ai
//!---------------------------------------------------------------------------------------------



const uint32_t OPM_WIDTH = 32;
const uint32_t WTM_WIDTH = 16;
const uint32_t NO_OF_CORES = 5;


#define GC_DEBUG_MODE
#define CNN_MODEL
#define USE_COMPILER_MICROCODE


const char modelname[] = "MODEL";


const uint32_t  MAX_INPUTS_PER_OPM_LOC_DNN = 20;
const uint32_t  MAX_INPUTGRIDS_PER_FRAME = 13;
const uint32_t  MAX_INPUTS_PER_OPM_LOC_CNN = 31;
const uint32_t  MAX_KERNELS_PER_SPLIT = 20;
const uint32_t MAX_OPM_LOCS = 8;


uint32_t N_OF_FRAMES;
uint32_t TOTAL_INPUTS;
uint32_t MAX_INPUTS_PER_BATCH;
uint32_t N_OF_FEATURES;
uint32_t N_OF_INPUTS_PER_OPM_LOC;


uint32_t* v_INPUTS = NULL;
uint32_t* v_OUTPUTS = NULL;


const uint32_t v_INPUTS_FLAT[] = 
{
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  12,  41,
 146, 146,  48,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  12, 129, 253, 253, 253,
 250, 163,  18,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0, 133, 253, 253, 253, 253, 253, 253,
 229,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0, 101, 253, 252, 145, 102, 107, 237, 253, 247,
 128,  10,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0, 181, 253, 167,   0,   0,   0,  61, 235, 253, 253, 163,
   5,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0, 255, 253,  43,   0,   0,   0,   0,  58, 193, 253, 253, 164,   4,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
 187, 253,  32,   0,   0,   0,   0,   0,  55, 236, 253, 253,  86,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 146, 253,
  32,   0, 100, 190,  87,  87,  87, 147, 253, 253, 123,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  94, 253,  78,  40,
 248, 253, 253, 253, 253, 253, 253, 253, 223,  84,  15,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,  14,  92,  12,  35, 240, 253,
 253, 253, 253, 253, 253, 253, 253, 253, 244,  89,  10,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  75, 161, 179, 253,
 253, 253, 253, 253, 253, 253, 253, 253, 209,  43,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  16,  16,  39,
  38,  16,  16, 145, 243, 253, 253, 185,  48,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,  20,  58,   0,   0,   0,   0,   0,   0,
   0,   0,  58, 209, 253, 253, 183,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,  77, 221, 247,  79,   0,   0,   0,   0,   0,   0,   0,
   0,  13, 219, 253, 240,  72,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,  90, 247, 253, 252,  57,   0,   0,   0,   0,   0,   0,   0,   0,
  53, 251, 253, 191,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0, 116, 253, 253,  59,   0,   0,   0,   0,   0,   0,   0,   0,  99, 252,
 253, 145,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  14,
 188, 253, 221, 158,  38,   0,   0,   0,   0, 111, 211, 246, 253, 253, 145,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  12, 221,
 246, 253, 251, 249, 249, 249, 249, 253, 253, 253, 253, 200,  19,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  95, 183,
 228, 253, 253, 253, 253, 253, 253, 195, 124,  23,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24,  37,
 138,  74, 126,  88,  37,   7,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
   0,   0,   0,   0 
};


const uint32_t N_OF_LAYERS = 4;
const uint32_t LAYER_TYPE[] = { 2,2,1,1, };
const int32_t N_OF_OUTPUT_NEURONS[] = { 20,30,30,10, };
const int32_t N_OF_BLOCKS[] =  { 1,1,1,1, };
const int32_t LAYER_ACT_FLAG[] =  { 0,0,0,3, };
const uint32_t packer_out = 1;
const uint32_t INPUT_DIM = 28;
const int32_t N_OF_CHANNELS[] =  { 1,20,30,30, };
const int32_t KERNEL_DIM[] =  { 5,5,30,10, };
const int32_t KERNEL_STRIDE[] =  { 2,3,1,1, };
const int32_t MAXPOOL_DIM[] =  { 2,0,0,0, };
const int32_t MAXPOOL_STRIDE[] =  { 2,1,1,1, };
const int32_t PADDING_SIZE[] =  { 0,0,0,0, };
const int32_t PADDING_VALUE[] =  { 0,0,0,0, };


#ifndef USE_COMPILER_MICROCODE
static uint32_t ucode_hex_generic [19][256] =
{

	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch0.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch1.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch2.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch3.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch4.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch5.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch6.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch7.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch8.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch9.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch10.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch11.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch12.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch13.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch14.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch15.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch16.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch17.hex.gpx"
	},
	{	
		#include "E:\Projects\MLIR_TEST\gpx10_ai_compiler.old.dense\examples\OUTPUT\MNIST_DEMO_MODEL\Batch18.hex.gpx"
	},
};
#endif

